language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="Deploy-2017.2.0f3" PROJECT_NAME="UnityExamplePackage" UNITY_PROJECT_PATH="UnityExample" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
- ./travis-build/run-tests.sh

after_success:
- ./travis-build/export-unity-package.sh

# before_deploy:
# - DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"
# 
# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: $DEPLOY_UNITYPACKAGE
#   skip_cleanup: true
#   overwrite: true
#   on:
#     tags: true 

before_deploy:
 - DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"


deploy:
  provider: releases
  api_key:
    secure: apdzdzZQGNcsOEE2exPmi29lLgHJwiwpnoQ4S2Y3J6lvLIVSJlQbT1W8gLzZpfV+jUbXl5yBMK3K1hF7o2Fhjpc5QF80+CDs7Z+M94FehtTzsHzRuPGLqZ+R/X2s7bsRft2Of9HfHpTilhTC2i7vHDKMEiz5gdkmQf+eGEn0LyrC7B8RdsckThzbv6jSnxZpImG1GVyg0suJaq0W8oKXCD1npUQwaiTLPlL7erNX+yu4vPmTwiOX3Np0eS9kfE4aQnzVjSTXAjo7tLrIpejCD0nTc5oUzV/+VBAZZ1u0YamAYMM7C5b+UE0/xoTUm2g2xipt5xyAyOEjxkeTkEWyMvVZoWUfpr+sWcWNYFANsRWaj2kkldlbt/Z/8zStGZveSlESWB0TRydS1Dsvjqg5ABZZ4VAIR8ZakCx1o092RXD0gk90Y9DJQWAv+UkzjkvU+7MkGajB+Ra/Dpy7geWrgvfNaIYPiojnovHxdizlwoJ9F4OX/LzKWJVJTm0fuazW7Ep3H5le8K5wJ9dHDIibG1awDRKPs15dxyocP122Mikfg1EfkEwhXoX9SUuoARzqmzF7tdMLu7eHi3n1H+BONeLYGxxBN01m3dlUi361PhRMc3yeIUjcE78TtNIGRiJPBCSG87duN4hPQ8nhEpxyA04/yBZCPfMJHVt3sLwGTFE=
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    repo: Torbilicious/InnoGamesGlobalGameJam2019
